# Generated by Django 3.2.8 on 2021-10-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='connection',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='connection'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
