# Generated by Django 3.2.8 on 2021-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20211020_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(default='master_class/no_image.jpg', null=True, upload_to='master_class/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Мастер класс',
                'verbose_name_plural': 'Мастер классы',
            },
        ),
    ]
