# Generated by Django 3.2.8 on 2021-10-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_masterclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterclass',
            options={'verbose_name': 'Мастер классы', 'verbose_name_plural': 'Мастер классы'},
        ),
        migrations.CreateModel(
            name='MasterClassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('image', models.ImageField(default='master_class_item/no_image.jpg', null=True, upload_to='master_class_item/', verbose_name='image')),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_class_item', to='landing.masterclass')),
            ],
            options={
                'verbose_name': 'Мастер класс',
                'verbose_name_plural': 'Мастер класс',
            },
        ),
    ]
