# Generated by Django 3.2.8 on 2021-10-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20211030_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('master_class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='landing.masterclassitem')),
            ],
        ),
    ]
