# Generated by Django 3.2.8 on 2021-10-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='text'),
        ),
    ]
