# Generated by Django 3.2.8 on 2021-10-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('image', models.ImageField(default='group_lessons/no_image.jpg', null=True, upload_to='group_lessons/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Групповые занятия',
                'verbose_name_plural': 'Групповые занятия',
            },
        ),
        migrations.CreateModel(
            name='GroupLessonsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('image', models.ImageField(default='group_lessons_item/no_image.jpg', null=True, upload_to='group_lessons_item/', verbose_name='image')),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons_item', to='landing.grouplessons')),
            ],
            options={
                'verbose_name': 'Групповое занятие',
                'verbose_name_plural': 'Групповое занятие',
            },
        ),
        migrations.CreateModel(
            name='GroupLessonsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('master_class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons_point', to='landing.grouplessonsitem')),
            ],
        ),
        migrations.CreateModel(
            name='GroupLessonsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='text')),
                ('master_class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons_price', to='landing.grouplessonsitem')),
            ],
        ),
        migrations.CreateModel(
            name='MasterClassPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('master_class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_class_point', to='landing.masterclassitem')),
            ],
        ),
        migrations.CreateModel(
            name='MasterClassPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='text')),
                ('master_class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_class_price', to='landing.masterclassitem')),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='master_class_item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
