# Generated by Django 3.2.8 on 2021-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20211101_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='masterclassitem',
            name='photo',
            field=models.ImageField(default='photo_teacher/no_image.jpg', null=True, upload_to='photo_teacher/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='masterclassitem',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='masterclassitem',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='teacher'),
        ),
    ]
