# Generated by Django 3.2.8 on 2021-10-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20211101_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplessonsitem',
            name='photo',
            field=models.ImageField(default='photo_teacher/no_image.jpg', null=True, upload_to='photo_teacher/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='grouplessonsitem',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='grouplessonsitem',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='teacher'),
        ),
    ]
