# Generated by Django 3.2.8 on 2021-10-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20211101_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplessonsitem',
            name='photo',
            field=models.ImageField(default='photo_teacher/no_image.jpg', null=True, upload_to='photo_teacher/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='masterclassitem',
            name='photo',
            field=models.ImageField(default='photo_teacher/no_image.jpg', null=True, upload_to='photo_teacher/', verbose_name='photo'),
        ),
    ]
