# Generated by Django 3.2.8 on 2021-11-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20211105_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclassprice',
            name='price_sale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по скидке'),
        ),
        migrations.AddField(
            model_name='masterclassprice',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
    ]
