# Generated by Django 3.2.8 on 2021-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_auto_20211125_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplessonsprice',
            name='units',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица'),
        ),
        migrations.AddField(
            model_name='masterclassprice',
            name='units',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица'),
        ),
    ]
