# Generated by Django 3.2.8 on 2021-11-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_auto_20211126_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('video', models.FileField(null=True, upload_to='video/', verbose_name='Видео')),
            ],
        ),
    ]
