# Generated by Django 3.2.8 on 2021-10-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галлерея', 'verbose_name_plural': 'Галлерея'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
